# Generated by Selenium IDE
import time

from selenium import webdriver


class TestTest01:
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_test01(self):
        self.driver.get("http://localhost:8383/voila/render/bandsplot-example.ipynb")
        self.driver.set_window_size(1280, 720)
        self.driver.save_screenshot("widget01.png")
        time.sleep(5)
        self.driver.execute_script("window.scrollTo(0, 1000)")
        self.driver.save_screenshot("widget02.png")


test = TestTest01()
test.setup_method("Chrome")
test.test_test01()
test.teardown_method("Chrome")
